### ISSUE TITLE
ASR processing failed: name "handle_openai_api_error" is not defined

### ISSUE THREAD

**Issue by weinfly** [murtaza-nasir/speakr#109]
Here's my .env file content:
# --- Text Generation Model ---
TEXT_MODEL_BASE_URL=http://192.168.11.84:11434/v1
TEXT_MODEL_API_KEY=ollama
TEXT_MODEL_NAME=nothink1

# --- ASR Endpoint (Local Whisper with Diarization) ---
USE_ASR_ENDPOINT=true
ASR_BASE_URL=http://whisper-asr:9000
ASR_DIARIZE=true
ASR_MIN_SPEAKERS=1
ASR_MAX_SPEAKERS=20

# --- Application Settings ---
ALLOW_REGISTRATION=false
TIMEZONE="UTC"
SUMMARY_MAX_TOKENS=8000
CHAT_MAX_TOKENS=5000

# --- Admin User (created on first run) ---
ADMIN_USERNAME=XXXX
ADMIN_EMAIL=XXXX
ADMIN_PASSWORD=

# --- Docker Settings ---
SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
UPLOAD_FOLDER=/data/uploads

#--- Other Settings ---
ENABLE_INQUIRE_MODE=true

**Comment by weinfly** [comment]
And this is my docker compose file content:

services:
  # ASR Webservice
  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    container_name: whisper-asr-webservice
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=large-v3
      - ASR_COMPUTE_TYPE=int8
      - ASR_ENGINE=whisperx
      - HF_TOKEN=# Required for diarization models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]  # Adjust GPU ID as needed
    restart: unless-stopped
    networks:
      - speakr-network

  # Speakr Application
  speakr:
    image: learnedmachine/speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    env_file:
      - .env
    volumes:
      - ./uploads:/data/uploads
      - ./instance:/data/instance
    depends_on:
      - whisper-asr
    networks:
      - speakr-network

networks:
  speakr-network:
    driver: bridge

**Comment by murtaza-nasir** [comment]
Thank you for reporting this! I've fixed the bad function call in the error handler.

However, this error only triggers when summary generation fails. Since you're using Ollama with `nothink1` model, there's likely an issue with your text generation endpoint or model configuration. With the fix now deployed, you should get a proper error message that explains what's actually failing with your LLM API.

Please pull the latest build and check the logs. You'll now see the actual error from your Ollama setup instead of this generic failure.

**Comment by weinfly** [comment]
Yes, I found that the content requiring summarization exceeded the LLM's limitations. After adjusting the LLM's limitations, the issue was resolved.
