### ISSUE TITLE
Can't run asr backend on RTX 5060Ti

### ISSUE THREAD

**Issue by ThreeLawThinker** [murtaza-nasir/speakr#112]
When I try to run the asr-backend on my RTX 5060 Ti, I get the following error:

NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
This causes the final error:
RuntimeError: CUDA error: no kernel image is available for execution on the device

Any ideas on how to fix it?

**Comment by murtaza-nasir** [comment]
I believe the 50 series cards need some extra steps. You can search for a solution or ask about this in the ASR repository.

**Comment by ThreeLawThinker** [comment]
I found a solution. The `asr` Docker container needs to be modified as follows:
```
FROM onerahmet/openai-whisper-asr-webservice:latest-gpu

# Update PyTorch in the application's virtual environment
RUN /app/.venv/bin/pip uninstall -y torch torchvision torchaudio && \
    /app/.venv/bin/pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 \
    --index-url https://download.pytorch.org/whl/cu128

WORKDIR /app
```
